spring.application.name=BASED-BLOG-BACKEND
spring.security.user.name=user
spring.security.user.password=test
server.port=8080

security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.expiration-time=3600000

#Mail Properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SUPPORT_EMAIL}
spring.mail.password=${APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.checkserveridentity=false
spring.mail.properties.mail.smtp.starttls.required=true

image.service.base-url=http://image.noobbasedswampizzo.com/


spring.config.import=optional:file:.env[.properties]
